### ISSUE TITLE
How to output the fractional hypertree decomposition?

### ISSUE THREAD

**Issue by shangqilu** [daajoe/frasmt#1]
Hi. Thanks for your code!
I can run your code now. 
But I currently do not know how to get the hypertree decomposition. I can only get the width.
Could you please help me? 

Thank you very much!

**Comment by daajoe** [comment]
If I remember correctly, the result (res) in frasmt/bin/fhtd:164 should contain a field td or decomposition (not entirely sure which one). Hence, res['td'] should allow you to access the decomposition. Then, the decomposition should have a method to output (htd_validate/htd_validate/decompositions/fhtd.py more precisely, https://github.com/daajoe/htd_validate/blob/76410c4ee79c1477db595ad37292459cfd8d75d9/htd_validate/decompositions/fhtd.py), which is implemented in ghtd.py as write or so.

**Comment by shangqilu** [comment]
Thank you very much!
I can get the hypertree decomposition now.
Actually, I found that the decomposition can be found in the log information.
